root = "."
tmp_dir = "tmp"

[build]
  cmd = "make build-cli-dev"
  bin = "/home/hersi/.nextdeploy/bin/nextdeploy"
  full_bin = ""
  include_ext = ["go", "toml"]
  exclude_dir = ["assets", "tmp", "vendor", "daemon", "docs"]
  include_dir = ["cli", "shared"]
  exclude_regex = ["_test.go"]
  delay = 1000
  stop_on_error = true
  log = "air.log"

[log]
  time = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = false
